### ISSUE TITLE
Anders report todos:

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/vapi#174] opened 2018-05-02 09:38 UTC
Tasks:
- [ ] Remove React from chapter 7.1.4 and upgrade with new pattern. Still MVC-pattern?
- [ ] Go through chapter 4.2.4 code standards to make sure we do not mention AirBnB styles since we do not use React

**Comment by sardred** [comment] 2018-05-04 09:14
Duplicate of #160

**Closed by sardred** 2018-05-04 09:14 UTC
